[package]
name = "shader"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = ["file_watcher"] }
bevy-inspector-egui = "0.30.0"
bevy_rts_camera = "0.9.1"
bevy_third_person_camera = "0.2.0"

[profile.dev.package."*"]
opt-level = 3
